/*!
 * CJT Ops Dashboard — standalone engine (no Claude/Anthropic dependency at runtime).
 * Hosted on GitHub, loaded by each client's GHL page via jsDelivr, so pushing an
 * update here updates every client's dashboard the next time their page loads.
 *
 * ============================================================================
 * WHAT TO PASTE INTO A CLIENT'S GHL SITE (Website/Funnel builder -> Custom
 * HTML/CSS/JS element):
 *
 *   <div id="cjt-dashboard-root"></div>
 *   <script>
 *     window.CJT_CONFIG = {
 *       locationId: "THEIR_GHL_LOCATION_ID",
 *       privateToken: "THEIR_GHL_PRIVATE_INTEGRATION_TOKEN",
 *       ghlBase: "https://app.THEIRDOMAIN.com",       // their GHL login domain
 *       dispatchPipelineName: "Towing Dispatch",        // must match exactly
 *       baseTowRate: 85,
 *       mileageRate: 3,
 *       setupUrl: "https://THEIRDOMAIN.com/setup"       // where "Setup" footer link goes
 *     };
 *   </script>
 *   <script src="https://cdn.jsdelivr.net/gh/YOUR_GH_ORG/cjt-ops-dashboard@main/dashboard.js"></script>
 *
 * IMPORTANT: use "@main" here, not "@latest". On jsDelivr, "@latest" for a
 * GitHub-sourced file resolves to the repo's latest git TAG (e.g. a GitHub
 * Release), not the newest commit — so the moment this repo publishes any
 * Release (for the browser-extension zips, say), "@latest" freezes
 * dashboard.js at whatever commit existed at that tag, silently serving
 * stale code until another Release is cut. "@main" always tracks the
 * newest commit on the main branch directly and has none of this trap.
 *
 * Everything else (markup, CSS, behavior) is generated by THIS file, so a
 * client never has to touch pasted code again after the first setup — only
 * this repo needs updating.
 *
 * UNVERIFIED — confirm against a real token before relying on this in front
 * of a client (see README.md "What still needs testing"):
 *   - Exact API Version header per endpoint (marked API_VERSIONS below)
 *   - Custom object property keys, esp. for a *different* client's schema
 *     (these were captured from CJ Taylor Towing's real GHL objects and will
 *     need re-checking if a new client's custom objects are shaped differently)
 *   - Pagination cap on /objects/:schemaKey/records/search
 * ============================================================================
 */
(function () {
  "use strict";

  // ---------------------------------------------------------------------
  // Config
  // ---------------------------------------------------------------------
  var DEFAULTS = {
    apiBase: "https://services.leadconnectorhq.com",
    ghlBase: "",
    locationId: "",
    privateToken: "",
    dispatchPipelineName: "Towing Dispatch",
    baseTowRate: 85,
    mileageRate: 3,
    setupUrl: "",
    objectKeys: {
      drivers: "driver_profiles",
      fleet: "trucks",
      maintenance: "maintenance_records",
      training: "training_records",
      quarters: "driver_quarters",
      aaa: "aaa_payments",
    },
    // Per-endpoint API "Version" header. GHL versions endpoints independently;
    // these are the values last confirmed against GHL's own docs/captured
    // traffic for this project. If a call starts failing with a 400 about
    // "invalid version", check GHL's current docs for that endpoint.
    apiVersions: {
      pipelines: "v3",
      opportunities: "2021-07-28",
      objects: "v3",
    },
  };

  var CONFIG = Object.assign({}, DEFAULTS, window.CJT_CONFIG || {});
  CONFIG.objectKeys = Object.assign({}, DEFAULTS.objectKeys, (window.CJT_CONFIG || {}).objectKeys || {});
  CONFIG.apiVersions = Object.assign({}, DEFAULTS.apiVersions, (window.CJT_CONFIG || {}).apiVersions || {});
  // Optional screen lock. passcodeHash is a SHA-256 hex digest of the shared
  // company passcode (the Setup page generates this — never put the plain
  // passcode in config). Leave passcodeHash unset to skip the lock entirely.
  // This is a deterrent against a screen left open in the shop, not real
  // cryptographic protection — anyone who can already read this page's
  // source can read the hash too. It stops a passerby, not a determined
  // technical attacker; token scoping/rotation (see README) is what protects
  // against that.
  CONFIG.passcodeHash = CONFIG.passcodeHash || "";
  CONFIG.idleLockMinutes = CONFIG.idleLockMinutes || 10;

  function ghlUrl(path) {
    return CONFIG.ghlBase + "/v2/location/" + CONFIG.locationId + path;
  }

  // ---------------------------------------------------------------------
  // GHL API client
  // ---------------------------------------------------------------------
  function ghlApi(path, opts) {
    opts = opts || {};
    var headers = {
      Authorization: "Bearer " + CONFIG.privateToken,
      Version: opts.version || CONFIG.apiVersions.objects,
    };
    if (opts.body) headers["Content-Type"] = "application/json";
    return fetch(CONFIG.apiBase + path, {
      method: opts.method || "GET",
      headers: headers,
      body: opts.body ? JSON.stringify(opts.body) : undefined,
    }).then(function (res) {
      if (!res.ok) {
        return res
          .text()
          .then(function (t) {
            throw new Error("GHL API " + res.status + " " + path + ": " + t.slice(0, 300));
          });
      }
      return res.json();
    });
  }

  function qs(params) {
    return Object.keys(params)
      .filter(function (k) { return params[k] !== undefined && params[k] !== null && params[k] !== ""; })
      .map(function (k) { return encodeURIComponent(k) + "=" + encodeURIComponent(params[k]); })
      .join("&");
  }

  function loadPipelines() {
    return ghlApi("/opportunities/pipelines?" + qs({ locationId: CONFIG.locationId }), { version: CONFIG.apiVersions.pipelines }).then(function (res) {
      return res.pipelines || [];
    });
  }

  // Paginates /opportunities/search for a single pipeline. Stops when a page
  // comes back shorter than the page size, or after a hard safety cap.
  function loadAllOpportunities(pipelineId) {
    var limit = 100;
    var page = 1;
    var all = [];
    function next() {
      var url =
        "/opportunities/search?" +
        qs({ location_id: CONFIG.locationId, pipeline_id: pipelineId, status: "all", limit: limit, page: page });
      return ghlApi(url, { version: CONFIG.apiVersions.opportunities }).then(function (res) {
        var batch = res.opportunities || [];
        all = all.concat(batch);
        if (batch.length < limit || page > 20) return all;
        page += 1;
        return next();
      });
    }
    return next();
  }

  // GHL's REST API needs a custom object's schemaKey fully qualified as
  // "custom_objects.<key>" in the URL path (confirmed 2026-09-17 against a
  // real location's GET /objects/ listing — a bare key like "trucks" is
  // rejected with 400 "Invalid Key Passed"). CONFIG.objectKeys stays as the
  // short/bare form because ghlUrl()'s "open in GHL" deep-links use that
  // same short form in their own, unrelated URL scheme (/v2/location/:id/
  // objects/:key/list) — only the REST API calls need this prefix, so it's
  // applied here at the point of use rather than baked into CONFIG.objectKeys.
  function objectSchemaKey(shortKey) {
    return "custom_objects." + shortKey;
  }

  // Paginates POST /objects/:schemaKey/records/search using searchAfter.
  function loadAllObjectRecords(schemaKey) {
    var pageLimit = 100;
    var all = [];
    function next(searchAfter) {
      var body = { locationId: CONFIG.locationId, page: 1, pageLimit: pageLimit, query: "" };
      if (searchAfter) body.searchAfter = searchAfter;
      return ghlApi("/objects/" + objectSchemaKey(schemaKey) + "/records/search", { method: "POST", version: CONFIG.apiVersions.objects, body: body }).then(function (res) {
        var batch = res.records || [];
        all = all.concat(batch);
        if (batch.length < pageLimit || all.length > 5000) return all;
        var last = batch[batch.length - 1];
        return next(last && last.searchAfter);
      });
    }
    return next(null);
  }

  function propVal(v) {
    // Currency-shaped properties come back as {currency, value}; everything
    // else is a plain scalar.
    if (v && typeof v === "object" && "value" in v) return v.value;
    return v;
  }

  // ---------------------------------------------------------------------
  // Property mappers: GHL record -> the row shape the existing UI expects
  // ---------------------------------------------------------------------
  function mapDriver(rec) {
    var p = rec.properties || {};
    return {
      recordId: rec.id,
      name: p.driver_name,
      driverId: p.driver_id,
      status: p.employment_status,
      type: p.employment_type,
      hireDate: p.hire_date,
      email: p.email,
    };
  }

  function mapTruck(rec) {
    var p = rec.properties || {};
    return {
      recordId: rec.id,
      unit: p.unit_number,
      yr: p.year,
      make: p.make,
      model: p.model,
      status: p.status,
      mileage: p.current_mileage,
      driver: p.primary_driver,
      nextService: p.next_service_date,
      regExp: p.registration_expiration,
      insExp: p.insurance_expiration,
    };
  }

  function mapMaintenance(rec) {
    var p = rec.properties || {};
    return {
      recordId: rec.id,
      id: p.maintenance_id,
      truck: p.truck_unit,
      type: p.maintenance_type,
      serviceDate: p.service_date,
      cost: propVal(p.cost),
      status: p.status,
      nextService: p.next_service_date,
      provider: p.service_provider,
    };
  }

  function mapTraining(rec) {
    var p = rec.properties || {};
    return {
      recordId: rec.id,
      id: p.training_id,
      driver: p.driver_name,
      title: p.training_title,
      type: p.training_type,
      date: p.training_date,
      status: p.status,
    };
  }

  function mapQuarter(rec) {
    var p = rec.properties || {};
    return {
      recordId: rec.id,
      driver: p.driver_name,
      quarter: p.quarter,
      year: p.year,
      completedJobs: p.completed_tow_jobs,
      totalJobs: p.total_tow_jobs,
      rating: p.performance_rating,
      status: p.status,
      revenue: propVal(p.total_revenue),
      commission: propVal(p.commission_earned),
      netCommission: propVal(p.net_commission),
    };
  }

  function mapAaa(rec) {
    var p = rec.properties || {};
    var gross = propVal(p.gross_paid_amount);
    var expected = propVal(p.expected_tow_amount);
    var diff = p.payment_difference_value;
    if (diff === undefined && gross != null && expected != null) diff = gross - expected;
    return {
      recordId: rec.id,
      id: p.aaa_payment_id,
      wo: p.work_order_number,
      status: p.reconciliation_status,
      gross: gross,
      expected: expected,
      diff: diff,
      reason: p.exception_reason || (diff > 0 ? "Overpaid by AAA" : diff < 0 ? "Underpaid by AAA" : null),
    };
  }

  // ---------------------------------------------------------------------
  // State + loaders
  // ---------------------------------------------------------------------
  var state = {
    meta: null,
    aaaSummary: null,
    aaaSamples: null,
    dispatch: null,
    drivers: null,
    fleet: null,
    maintenance: null,
    training: null,
    quarters: null,
  };

  var stageNameById = {};

  function loadDispatch() {
    return loadPipelines().then(function (pipelines) {
      var pipeline = pipelines.filter(function (p) {
        return (p.name || "").toLowerCase() === CONFIG.dispatchPipelineName.toLowerCase();
      })[0];
      if (!pipeline) throw new Error('No pipeline named "' + CONFIG.dispatchPipelineName + '" found in this GHL location.');
      stageNameById = {};
      (pipeline.stages || []).forEach(function (s) { stageNameById[s.id] = s.name; });
      return loadAllOpportunities(pipeline.id).then(function (opps) {
        var stageCounts = {};
        var rows = opps.map(function (o) {
          var stageName = stageNameById[o.pipelineStageId] || o.pipelineStageId;
          stageCounts[stageName] = (stageCounts[stageName] || 0) + 1;
          return {
            name: o.name,
            stage: stageName,
            status: o.status,
            value: o.monetaryValue,
            updatedAt: o.updatedAt,
            contactId: o.contactId,
          };
        });
        state.dispatch = {
          opportunities: rows,
          stageCounts: stageCounts,
          pipelineName: pipeline.name,
          total: rows.length,
        };
      });
    });
  }

  function loadDrivers() {
    return loadAllObjectRecords(CONFIG.objectKeys.drivers).then(function (recs) {
      var rows = recs.map(mapDriver);
      state.drivers = { records: rows, total: rows.length };
    });
  }

  function loadFleet() {
    return loadAllObjectRecords(CONFIG.objectKeys.fleet).then(function (recs) {
      var rows = recs.map(mapTruck);
      state.fleet = { records: rows, total: rows.length };
    });
  }

  function loadMaintenance() {
    return loadAllObjectRecords(CONFIG.objectKeys.maintenance).then(function (recs) {
      state.maintenance = { records: recs.map(mapMaintenance) };
    });
  }

  function loadTraining() {
    return loadAllObjectRecords(CONFIG.objectKeys.training).then(function (recs) {
      state.training = { records: recs.map(mapTraining) };
    });
  }

  function loadQuarters() {
    return loadAllObjectRecords(CONFIG.objectKeys.quarters).then(function (recs) {
      state.quarters = { records: recs.map(mapQuarter) };
    });
  }

  function loadAaa() {
    return loadAllObjectRecords(CONFIG.objectKeys.aaa).then(function (recs) {
      var rows = recs.map(mapAaa);
      var statusCounts = {};
      var missingWo = 0;
      rows.forEach(function (r) {
        var key = (r.status || "unknown").toLowerCase();
        statusCounts[key] = (statusCounts[key] || 0) + 1;
        if (!r.wo) missingWo += 1;
      });
      var exceptions = rows
        .filter(function (r) { return (r.status || "").toLowerCase() === "exception"; })
        .sort(function (a, b) { return Math.abs(Number(b.diff) || 0) - Math.abs(Number(a.diff) || 0); })
        .slice(0, 25);
      var matchedSample = rows.filter(function (r) { return (r.status || "").toLowerCase() === "matched"; }).slice(0, 25);
      state.aaaSummary = { total: rows.length, status_counts: statusCounts, missing_work_order: missingWo };
      state.aaaSamples = { exceptions: exceptions, unmatched: matchedSample };
    });
  }

  function loadMeta() {
    var counts = {
      drivers: (state.drivers && state.drivers.total) || 0,
      fleet: (state.fleet && state.fleet.total) || 0,
    };
    state.meta = { lastSynced: new Date().toISOString(), objectCounts: counts };
  }

  function loadAll() {
    return Promise.all([loadDispatch(), loadDrivers(), loadFleet(), loadMaintenance(), loadTraining(), loadQuarters(), loadAaa()]).then(loadMeta);
  }

  // ---------------------------------------------------------------------
  // (UI layer below is unchanged from the previous Claude-Artifact build —
  // same render functions, same CSS, same click-through behavior — only the
  // data layer above and the init/refresh wiring at the bottom changed.)
  // ---------------------------------------------------------------------

  // Everything the page needs — CSS and markup — ships inline in this one
  // file on purpose: one file on GitHub, one script tag in GHL, nothing
  // else to keep in sync.
  var CSS_TEXT = [
    ':root{--bg:#f3f5f8;--panel:#fff;--border:#e1e5eb;--text:#1a2130;--text-dim:#626b7a;--accent:#1d4ed8;--accent-soft:#e7edfc;--accent-strong:#1739ab;--good:#15803d;--good-soft:#e1f4e8;--warn:#b45309;--warn-soft:#fbeed9;--crit:#b91c1c;--crit-soft:#fbe4e2;--info:#0e7490;--info-soft:#dff2f4;--chip-bg:#eef1f5;--shadow:0 1px 2px rgba(20,25,40,.05),0 2px 10px rgba(20,25,40,.06)}',
    '#cjt-dashboard-root *{box-sizing:border-box}',
    '#cjt-dashboard-root{background:var(--bg);color:var(--text);font-family:"IBM Plex Sans",-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;padding:22px 16px 52px;position:relative}',
    '#cjt-dashboard-root .mono{font-family:"IBM Plex Mono",ui-monospace,SFMono-Regular,Menlo,monospace;font-variant-numeric:tabular-nums}',
    '#cjt-dashboard-root .wrap{max-width:1160px;margin:0 auto}',
    '#cjt-dashboard-root header.top{display:flex;flex-wrap:wrap;align-items:center;justify-content:space-between;gap:10px;margin-bottom:4px}',
    '#cjt-dashboard-root .brand{display:flex;align-items:baseline;gap:10px}',
    '#cjt-dashboard-root header.top h1{font-size:21px;margin:0;font-weight:700;letter-spacing:-.01em}',
    '#cjt-dashboard-root .brand .tag{font-size:11px;font-weight:600;text-transform:uppercase;letter-spacing:.06em;color:var(--accent);background:var(--accent-soft);padding:3px 8px;border-radius:5px}',
    '#cjt-dashboard-root .sync-wrap{display:flex;align-items:center;gap:10px}',
    '#cjt-dashboard-root .sync-badge{font-size:12px;color:var(--text-dim);display:flex;align-items:center;gap:6px;font-family:"IBM Plex Mono",monospace}',
    '#cjt-dashboard-root .sync-dot{width:7px;height:7px;border-radius:50%;background:var(--good);flex-shrink:0;box-shadow:0 0 0 3px var(--good-soft);position:relative}',
    '#cjt-dashboard-root .sync-dot::after{content:"";position:absolute;inset:-4px;border-radius:50%;background:var(--good);animation:cjtPing 1.8s cubic-bezier(0,0,.2,1) infinite}',
    '#cjt-dashboard-root .iconBtn{appearance:none;border:1px solid var(--border);background:var(--panel);color:var(--text);font-family:inherit;font-size:12.5px;font-weight:600;padding:6px 12px;border-radius:8px;cursor:pointer;display:inline-flex;align-items:center;gap:6px;box-shadow:var(--shadow);text-decoration:none}',
    '#cjt-dashboard-root .iconBtn:hover{border-color:var(--accent);color:var(--accent)}',
    '#cjt-dashboard-root .iconBtn svg{width:14px;height:14px}',
    '#cjt-dashboard-root #refreshBtn.spinning svg{animation:cjtSpin .8s linear infinite}',
    '#cjt-dashboard-root .sub{color:var(--text-dim);font-size:13px;margin-top:6px;margin-bottom:22px;max-width:74ch;line-height:1.55}',
    '#cjt-dashboard-root .pulse-strip{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:10px;margin-bottom:14px}',
    '#cjt-dashboard-root .pulse-tile{background:var(--panel);border:1px solid var(--border);border-radius:11px;padding:12px 14px;display:flex;flex-direction:column;gap:3px;transition:transform .15s ease,box-shadow .15s ease,border-color .15s ease}',
    '#cjt-dashboard-root .pulse-tile:hover{transform:translateY(-1px);border-color:var(--accent);box-shadow:0 4px 12px rgba(20,25,40,.08)}',
    '#cjt-dashboard-root .pulse-label{font-size:10.5px;font-weight:600;text-transform:uppercase;letter-spacing:.06em;color:var(--text-dim);display:flex;align-items:center;gap:5px}',
    '#cjt-dashboard-root .pulse-label .dot{width:6px;height:6px;border-radius:50%;flex-shrink:0}',
    '#cjt-dashboard-root .pulse-label .dot.good{background:var(--good)}#cjt-dashboard-root .pulse-label .dot.warn{background:var(--warn)}#cjt-dashboard-root .pulse-label .dot.info{background:var(--info)}',
    '#cjt-dashboard-root .pulse-value{font-family:"IBM Plex Mono",monospace;font-size:19px;font-weight:700}',
    '#cjt-dashboard-root .pulse-sub{font-size:11.5px;color:var(--text-dim)}',
    '#cjt-dashboard-root .home{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:14px}',
    '#cjt-dashboard-root .hubcard{text-align:left;background:var(--panel);border:1px solid var(--border);border-radius:14px;padding:20px;box-shadow:var(--shadow);cursor:pointer;display:flex;flex-direction:column;gap:10px;font-family:inherit;color:inherit;transition:transform .12s ease,box-shadow .12s ease,border-color .12s ease}',
    '#cjt-dashboard-root .hubcard:hover{transform:translateY(-2px);border-color:var(--accent);box-shadow:0 6px 18px rgba(20,25,40,.10)}',
    '#cjt-dashboard-root .hubcard:focus-visible{outline:2px solid var(--accent);outline-offset:2px}',
    '#cjt-dashboard-root .hubcard .htitle{font-size:15px;font-weight:700;display:flex;align-items:center;justify-content:space-between;gap:8px}',
    '#cjt-dashboard-root .hubcard .htitle-left{display:flex;align-items:center;gap:10px}',
    '#cjt-dashboard-root .hubcard .icon{width:38px;height:38px;border-radius:10px;background:var(--accent-soft);color:var(--accent);display:flex;align-items:center;justify-content:center;flex-shrink:0}',
    '#cjt-dashboard-root .hubcard .icon svg{width:20px;height:20px}',
    '#cjt-dashboard-root .hubcard .hvalue{font-family:"IBM Plex Mono",monospace;font-size:22px;font-weight:700}',
    '#cjt-dashboard-root .hvalue.pulseIn{animation:cjtGlow .7s ease}',
    '#cjt-dashboard-root .hubcard .hdetail{font-size:12.5px;color:var(--text-dim);line-height:1.5;min-height:34px}',
    '#cjt-dashboard-root .hubcard .chevron{color:var(--accent);font-size:12.5px;font-weight:600}',
    '#cjt-dashboard-root .livepill{font-size:10px;font-weight:700;text-transform:uppercase;letter-spacing:.05em;color:var(--good);background:var(--good-soft);padding:3px 7px;border-radius:999px;white-space:nowrap}',
    '#cjt-dashboard-root .crumb{display:flex;align-items:center;gap:8px;margin-bottom:6px;font-size:13px}',
    '#cjt-dashboard-root .crumbBtn{background:none;border:none;color:var(--accent);font-weight:600;font-size:13px;cursor:pointer;padding:0;font-family:inherit}',
    '#cjt-dashboard-root .crumbBtn:hover{text-decoration:underline}',
    '#cjt-dashboard-root .crumbSep{color:var(--text-dim);opacity:.6}#cjt-dashboard-root .crumbCurrent{color:var(--text-dim)}',
    '#cjt-dashboard-root .section-title{font-size:19px;font-weight:700;margin:6px 0 2px}',
    '#cjt-dashboard-root .section-desc{font-size:13px;color:var(--text-dim);margin-bottom:16px;max-width:70ch;line-height:1.5}',
    '#cjt-dashboard-root .subnav{display:flex;gap:6px;flex-wrap:wrap;margin-bottom:18px}',
    '#cjt-dashboard-root .subnav button{appearance:none;border:1px solid var(--border);background:var(--panel);color:var(--text-dim);font-family:inherit;font-size:13px;font-weight:600;padding:7px 14px;border-radius:999px;cursor:pointer}',
    '#cjt-dashboard-root .subnav button.active{background:var(--accent);border-color:var(--accent);color:#fff}',
    '#cjt-dashboard-root .subnav button:hover:not(.active){border-color:var(--accent);color:var(--accent)}',
    '#cjt-dashboard-root .panel-head{display:flex;flex-wrap:wrap;align-items:center;justify-content:space-between;gap:10px;margin-bottom:14px}',
    '#cjt-dashboard-root .panel-note{font-size:12.5px;color:var(--text-dim);line-height:1.55;flex:1 1 340px}',
    '#cjt-dashboard-root .panel-note b{color:var(--text);font-weight:600}',
    '#cjt-dashboard-root .live-tag{color:var(--good);font-weight:700}#cjt-dashboard-root .demo-tag{color:var(--text-dim);font-style:italic}',
    '#cjt-dashboard-root .panel-actions{display:flex;gap:8px;flex-wrap:wrap}',
    '#cjt-dashboard-root .ghllink{font-size:12.5px;font-weight:600;color:var(--accent);background:var(--accent-soft);border-radius:8px;padding:8px 13px;text-decoration:none;white-space:nowrap;flex-shrink:0;display:inline-flex;align-items:center;gap:5px}',
    '#cjt-dashboard-root .ghllink:hover{filter:brightness(.96)}#cjt-dashboard-root .ghllink.primary{background:var(--accent);color:#fff}#cjt-dashboard-root .ghllink.primary:hover{background:var(--accent-strong)}',
    '#cjt-dashboard-root .searchRow{margin-bottom:10px}',
    '#cjt-dashboard-root .searchInput{width:100%;max-width:320px;border:1px solid var(--border);border-radius:8px;padding:8px 12px;font-size:13px;font-family:inherit;background:var(--panel);color:var(--text)}',
    '#cjt-dashboard-root .searchInput:focus{outline:2px solid var(--accent);outline-offset:1px;border-color:var(--accent)}',
    '#cjt-dashboard-root .chipRow{display:flex;flex-wrap:wrap;gap:8px;margin-bottom:16px}',
    '#cjt-dashboard-root .chip{font-size:12.5px;font-weight:600;padding:5px 11px;border-radius:999px;background:var(--chip-bg);color:var(--text);display:inline-flex;align-items:center;gap:6px;transition:transform .15s ease}',
    '#cjt-dashboard-root .chip:hover{transform:translateY(-1px)}',
    '#cjt-dashboard-root .chip b{font-weight:700;font-family:"IBM Plex Mono",monospace}',
    '#cjt-dashboard-root .chip.accent{background:var(--accent-soft);color:var(--accent)}#cjt-dashboard-root .chip.info{background:var(--info-soft);color:var(--info)}#cjt-dashboard-root .chip.amber{background:var(--warn-soft);color:var(--warn)}#cjt-dashboard-root .chip.red{background:var(--crit-soft);color:var(--crit)}',
    '#cjt-dashboard-root .subhead{font-size:13px;font-weight:700;margin:20px 0 8px;color:var(--text)}',
    '#cjt-dashboard-root .tableWrap{background:var(--panel);border:1px solid var(--border);border-radius:12px;overflow-x:auto;box-shadow:var(--shadow)}',
    '#cjt-dashboard-root table{border-collapse:collapse;width:100%;font-size:13px;min-width:480px}',
    '#cjt-dashboard-root thead th{text-align:left;font-size:10.5px;text-transform:uppercase;letter-spacing:.05em;color:var(--text-dim);font-weight:600;padding:11px 14px;border-bottom:1px solid var(--border);white-space:nowrap}',
    '#cjt-dashboard-root tbody td{padding:11px 14px;border-bottom:1px solid var(--border);white-space:nowrap}',
    '#cjt-dashboard-root tbody tr:last-child td{border-bottom:none}#cjt-dashboard-root tbody tr:hover{background:var(--chip-bg)}#cjt-dashboard-root tbody tr.clickable{cursor:pointer}',
    '#cjt-dashboard-root a.rowlink{color:var(--accent);text-decoration:none;font-weight:600}#cjt-dashboard-root a.rowlink:hover{text-decoration:underline}',
    '#cjt-dashboard-root a.rowlink::after{content:" \\2197";font-weight:400;opacity:.55;font-size:11px}',
    '#cjt-dashboard-root a.cellLink{display:block;color:inherit;text-decoration:none}',
    '#cjt-dashboard-root a.rowlink,#cjt-dashboard-root a.cellLink,#cjt-dashboard-root .miniRow,#cjt-dashboard-root tbody tr,#cjt-dashboard-root .subnav button,#cjt-dashboard-root .ghllink{transition:background-color .15s ease,color .15s ease,border-color .15s ease,transform .15s ease}',
    '#cjt-dashboard-root .status-pill{font-size:11px;font-weight:600;padding:3px 9px;border-radius:999px;background:var(--chip-bg);white-space:nowrap}',
    '#cjt-dashboard-root .status-active,#cjt-dashboard-root .status-matched,#cjt-dashboard-root .status-completed,#cjt-dashboard-root .status-resolved,#cjt-dashboard-root .status-finalized,#cjt-dashboard-root .status-paid,#cjt-dashboard-root .status-good{background:var(--good-soft);color:var(--good)}',
    '#cjt-dashboard-root .status-exception,#cjt-dashboard-root .status-cancelled,#cjt-dashboard-root .status-terminated,#cjt-dashboard-root .status-out_of_service,#cjt-dashboard-root .status-needs_improvement{background:var(--crit-soft);color:var(--crit)}',
    '#cjt-dashboard-root .status-unmatched,#cjt-dashboard-root .status-maintenance,#cjt-dashboard-root .status-pending,#cjt-dashboard-root .status-scheduled,#cjt-dashboard-root .status-in_progress,#cjt-dashboard-root .status-under_review,#cjt-dashboard-root .status-retired{background:var(--warn-soft);color:var(--warn)}',
    '#cjt-dashboard-root .status-open,#cjt-dashboard-root .status-lost{background:var(--info-soft);color:var(--info)}',
    '#cjt-dashboard-root .empty{padding:30px;text-align:center;color:var(--text-dim);font-size:13px}',
    '#cjt-dashboard-root .foot-note{margin-top:26px;font-size:12px;color:var(--text-dim);line-height:1.6}',
    '#cjt-dashboard-root .overview-heading{font-size:12.5px;font-weight:700;text-transform:uppercase;letter-spacing:.05em;color:var(--text-dim);margin:26px 0 10px}',
    '#cjt-dashboard-root .overview{display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:14px}',
    '#cjt-dashboard-root .miniPanel{background:var(--panel);border:1px solid var(--border);border-radius:14px;padding:16px 18px;box-shadow:var(--shadow)}',
    '#cjt-dashboard-root .miniTitle{font-size:12.5px;font-weight:700;color:var(--text);margin-bottom:10px}',
    '#cjt-dashboard-root .miniStat{font-size:12px;color:var(--text-dim);margin-bottom:8px}',
    '#cjt-dashboard-root .miniList{display:flex;flex-direction:column}',
    '#cjt-dashboard-root .miniRow{display:flex;align-items:center;justify-content:space-between;gap:10px;padding:8px 2px;border-bottom:1px solid var(--border);text-decoration:none;color:inherit}',
    '#cjt-dashboard-root .miniRow:last-child{border-bottom:none}#cjt-dashboard-root .miniRow.clickable{cursor:pointer;border-radius:8px}#cjt-dashboard-root .miniRow.clickable:hover{background:var(--chip-bg)}',
    '#cjt-dashboard-root .miniRowMain{display:block;min-width:0}',
    '#cjt-dashboard-root .miniRowTitle{display:block;font-size:12.5px;font-weight:600;color:var(--text);white-space:nowrap;overflow:hidden;text-overflow:ellipsis;max-width:230px}',
    '#cjt-dashboard-root .miniRowArrow{font-weight:400;opacity:.5;font-size:11px}#cjt-dashboard-root .miniRow.clickable:hover .miniRowArrow{opacity:1;color:var(--accent)}',
    '#cjt-dashboard-root .miniRowDetail{display:block;font-size:11px;color:var(--text-dim);margin-top:2px}',
    '#cjt-dashboard-root .miniRowBadge{display:inline-flex;flex-shrink:0}',
    '#cjt-dashboard-root .due-badge{font-size:10.5px;font-weight:700;padding:3px 8px;border-radius:999px;white-space:nowrap}',
    '#cjt-dashboard-root .due-overdue,#cjt-dashboard-root .due-today{background:var(--crit-soft);color:var(--crit);animation:cjtPulseOpacity 1.6s ease-in-out infinite}',
    '#cjt-dashboard-root .due-soon{background:var(--warn-soft);color:var(--warn)}#cjt-dashboard-root .due-later{background:var(--chip-bg);color:var(--text-dim)}',
    '@keyframes cjtFadeInUp{from{opacity:0;transform:translateY(10px)}to{opacity:1;transform:translateY(0)}}',
    '@keyframes cjtPulseOpacity{0%,100%{opacity:1}50%{opacity:.5}}',
    '@keyframes cjtPing{0%{transform:scale(1);opacity:.55}75%,100%{transform:scale(2.6);opacity:0}}',
    '@keyframes cjtGlow{0%{text-shadow:0 0 0 rgba(29,78,216,0)}40%{text-shadow:0 0 14px var(--accent-soft)}100%{text-shadow:0 0 0 rgba(29,78,216,0)}}',
    '@keyframes cjtSpin{from{transform:rotate(0)}to{transform:rotate(360deg)}}',
    '#cjt-dashboard-root .home .hubcard,#cjt-dashboard-root .overview .miniPanel,#cjt-dashboard-root .pulse-strip .pulse-tile{animation:cjtFadeInUp .4s cubic-bezier(.2,.7,.3,1) both}',
    '#cjt-dashboard-root .home .hubcard:nth-child(1){animation-delay:.06s}#cjt-dashboard-root .home .hubcard:nth-child(2){animation-delay:.11s}#cjt-dashboard-root .home .hubcard:nth-child(3){animation-delay:.16s}#cjt-dashboard-root .home .hubcard:nth-child(4){animation-delay:.21s}',
    '#cjt-dashboard-root .animateIn{animation:cjtFadeInUp .3s cubic-bezier(.2,.7,.3,1) both}',
    '@media (prefers-reduced-motion:reduce){#cjt-dashboard-root *{animation-duration:.001s!important;animation-iteration-count:1!important;transition-duration:.001s!important}#cjt-dashboard-root .sync-dot::after{display:none}}',
    '#cjt-dashboard-root.cjtLocked .wrap{filter:blur(8px);pointer-events:none;user-select:none}',
    '#cjt-dashboard-root .cjtLockOverlay{position:fixed;inset:0;background:rgba(20,25,40,.6);display:none;align-items:center;justify-content:center;z-index:999999;padding:16px}',
    '#cjt-dashboard-root.cjtLocked .cjtLockOverlay{display:flex}',
    '#cjt-dashboard-root .cjtLockCard{background:var(--panel);border-radius:14px;padding:28px 26px;max-width:340px;width:100%;box-shadow:0 12px 40px rgba(0,0,0,.28);text-align:center}',
    '#cjt-dashboard-root .cjtLockTitle{font-size:17px;font-weight:700;margin-bottom:8px}',
    '#cjt-dashboard-root .cjtLockWarn{font-size:12.5px;color:var(--text-dim);line-height:1.5;margin-bottom:16px}',
    '#cjt-dashboard-root .cjtLockInput{width:100%;border:1px solid var(--border);border-radius:8px;padding:10px 12px;font-size:14px;margin-bottom:10px;font-family:inherit;text-align:center;box-sizing:border-box}',
    '#cjt-dashboard-root .cjtLockBtn{width:100%;background:var(--accent);color:#fff;border:none;border-radius:8px;padding:10px;font-weight:600;font-size:13.5px;cursor:pointer;font-family:inherit}',
    '#cjt-dashboard-root .cjtLockBtn:hover{background:var(--accent-strong)}',
    '#cjt-dashboard-root .cjtLockError{color:var(--crit);font-size:12px;margin-top:8px;min-height:14px}',
    '@media (max-width:480px){#cjt-dashboard-root .hubcard .hdetail{min-height:0}}'
  ].join("\n");

  var PAGE_HTML =
    '<div class="wrap">' +
    '<header class="top"><div class="brand"><h1>CJT Ops Dashboard</h1><span class="tag">Vallis Via</span></div>' +
    '<div class="sync-wrap"><div class="sync-badge"><span class="sync-dot"></span><span id="syncText">Loading…</span></div>' +
    '<button class="iconBtn" id="refreshBtn" type="button" title="Refresh from GHL"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M20 11A8 8 0 0 0 5.7 6.3L4 8"></path><path d="M4 4v4h4"></path><path d="M4 13a8 8 0 0 0 14.3 4.7L20 16"></path><path d="M20 20v-4h-4"></path></svg>Refresh</button>' +
    '<a class="iconBtn" id="setupLink" href="#" title="Setup"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="3"></circle><path d="M19.4 15a1.7 1.7 0 0 0 .3 1.9l.1.1a2 2 0 1 1-2.8 2.8l-.1-.1a1.7 1.7 0 0 0-1.9-.3 1.7 1.7 0 0 0-1 1.6V21a2 2 0 1 1-4 0v-.1a1.7 1.7 0 0 0-1-1.6 1.7 1.7 0 0 0-1.9.3l-.1.1a2 2 0 1 1-2.8-2.8l.1-.1a1.7 1.7 0 0 0 .3-1.9 1.7 1.7 0 0 0-1.6-1H3a2 2 0 1 1 0-4h.1a1.7 1.7 0 0 0 1.6-1 1.7 1.7 0 0 0-.3-1.9l-.1-.1a2 2 0 1 1 2.8-2.8l.1.1a1.7 1.7 0 0 0 1.9.3H9a1.7 1.7 0 0 0 1-1.6V3a2 2 0 1 1 4 0v.1a1.7 1.7 0 0 0 1 1.6 1.7 1.7 0 0 0 1.9-.3l.1-.1a2 2 0 1 1 2.8 2.8l-.1.1a1.7 1.7 0 0 0-.3 1.9V9a1.7 1.7 0 0 0 1.6 1H21a2 2 0 1 1 0 4h-.1a1.7 1.7 0 0 0-1.6 1z"></path></svg>Setup</a>' +
    "</div></header>" +
    '<div class="sub" id="introText">CJ Taylor Towing — a working view of GoHighLevel, reading live from your GHL account. Pick a section below.</div>' +
    '<div id="pulseStrip" class="pulse-strip" hidden></div>' +
    '<div id="home" class="home"></div>' +
    '<div class="overview-heading" id="overviewHeading" hidden>At a glance</div>' +
    '<div id="overview" class="overview" hidden></div>' +
    '<div id="section" hidden><div class="crumb" id="crumb"></div><div class="section-title" id="sectionTitle"></div><div class="section-desc" id="sectionDesc"></div><div class="subnav" id="subnav" hidden></div><div id="sectionBody"></div></div>' +
    '<div class="foot-note" id="footNote">Rows and buttons marked <span class="mono">↗</span> open GoHighLevel in a new tab, where changes are made.</div>' +
    "</div>";

  function sha256Hex(str) {
    var enc = new TextEncoder().encode(str);
    return crypto.subtle.digest("SHA-256", enc).then(function (buf) {
      return Array.prototype.map
        .call(new Uint8Array(buf), function (b) { return b.toString(16).padStart(2, "0"); })
        .join("");
    });
  }

  // Optional screen lock: shows a blurred overlay requiring CONFIG.passcodeHash
  // before the page is usable, and re-locks after CONFIG.idleLockMinutes of no
  // activity. See the CONFIG.passcodeHash comment above for what this is (and
  // isn't) protecting against. Calls onFirstUnlock() once, the first time the
  // page becomes usable in this tab.
  function initSecurity(root, onFirstUnlock) {
    if (!CONFIG.passcodeHash) {
      onFirstUnlock();
      return;
    }
    var SESSION_KEY = "cjt_dash_unlocked";
    var idleMs = CONFIG.idleLockMinutes * 60 * 1000;

    var overlay = document.createElement("div");
    overlay.className = "cjtLockOverlay";
    overlay.innerHTML =
      '<div class="cjtLockCard"><div class="cjtLockTitle">Locked</div>' +
      '<div class="cjtLockWarn">Don’t leave this page open and unattended — it shows live dispatch, driver, and payment data.</div>' +
      '<input type="password" class="cjtLockInput" id="cjtLockInput" placeholder="Company passcode" autocomplete="off">' +
      '<button type="button" class="cjtLockBtn" id="cjtLockBtn">Unlock</button>' +
      '<div class="cjtLockError" id="cjtLockError" aria-live="polite"></div></div>';
    root.appendChild(overlay);

    var input = overlay.querySelector("#cjtLockInput");
    var btn = overlay.querySelector("#cjtLockBtn");
    var errEl = overlay.querySelector("#cjtLockError");
    var firstRun = true;
    var lastActivity = Date.now();

    function lock() {
      root.classList.add("cjtLocked");
      try { sessionStorage.removeItem(SESSION_KEY); } catch (e) {}
      input.value = "";
      errEl.textContent = "";
      setTimeout(function () { input.focus(); }, 50);
    }

    function unlock() {
      root.classList.remove("cjtLocked");
      errEl.textContent = "";
      input.value = "";
      try { sessionStorage.setItem(SESSION_KEY, "1"); } catch (e) {}
      lastActivity = Date.now();
      if (firstRun) {
        firstRun = false;
        onFirstUnlock();
      }
    }

    function attempt() {
      var val = input.value;
      btn.disabled = true;
      sha256Hex(val)
        .then(function (h) {
          btn.disabled = false;
          if (h === CONFIG.passcodeHash) unlock();
          else {
            errEl.textContent = "Incorrect passcode.";
            input.value = "";
            input.focus();
          }
        })
        .catch(function () { btn.disabled = false; });
    }

    btn.addEventListener("click", attempt);
    input.addEventListener("keydown", function (e) { if (e.key === "Enter") attempt(); });

    var alreadyUnlocked = false;
    try { alreadyUnlocked = sessionStorage.getItem(SESSION_KEY) === "1"; } catch (e) {}
    if (alreadyUnlocked) {
      firstRun = false;
      onFirstUnlock();
    } else {
      root.classList.add("cjtLocked");
      setTimeout(function () { input.focus(); }, 50);
    }

    ["mousemove", "keydown", "click", "scroll", "touchstart"].forEach(function (evt) {
      document.addEventListener(evt, function () { lastActivity = Date.now(); }, { passive: true });
    });
    function checkIdle() {
      if (!root.classList.contains("cjtLocked") && Date.now() - lastActivity > idleMs) lock();
    }
    setInterval(checkIdle, 15000);
    document.addEventListener("visibilitychange", function () { if (!document.hidden) checkIdle(); });
  }

  function mount() {
    var root = document.getElementById("cjt-dashboard-root");
    if (!root) {
      console.error("[CJT Dashboard] #cjt-dashboard-root not found on the page.");
      return;
    }
    var styleEl = document.createElement("style");
    styleEl.textContent = CSS_TEXT;
    document.head.appendChild(styleEl);
    var fontLink = document.createElement("link");
    fontLink.rel = "stylesheet";
    fontLink.href = "https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@400;500;600;700&family=IBM+Plex+Mono:wght@400;500;600&display=swap";
    document.head.appendChild(fontLink);
    root.innerHTML = PAGE_HTML;
    initSecurity(root, function () { runApp(root); });
  }

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", mount);
  } else {
    mount();
  }

  function runApp(root) {
    // ---- everything from here down is the same UI logic as before ----
    var LIST_URLS = {
      dispatch: ghlUrl("/opportunities/list"),
      aaa: ghlUrl("/objects/" + CONFIG.objectKeys.aaa + "/list"),
      drivers: ghlUrl("/objects/" + CONFIG.objectKeys.drivers + "/list"),
      fleet: ghlUrl("/objects/" + CONFIG.objectKeys.fleet + "/list"),
      maintenance: ghlUrl("/objects/" + CONFIG.objectKeys.maintenance + "/list"),
      training: ghlUrl("/objects/" + CONFIG.objectKeys.training + "/list"),
      quarters: ghlUrl("/objects/" + CONFIG.objectKeys.quarters + "/list"),
    };

    var LINK_FNS = {
      dispatch: function (r) { return r.contactId ? ghlUrl("/contacts/detail/" + r.contactId) : null; },
      fleet: function (r) { return r.recordId ? ghlUrl("/objects/" + CONFIG.objectKeys.fleet + "/list?recordId=" + r.recordId) : LIST_URLS.fleet; },
      drivers: function (r) { return r.recordId ? ghlUrl("/objects/" + CONFIG.objectKeys.drivers + "/list?recordId=" + r.recordId) : LIST_URLS.drivers; },
      quarters: function (r) { return r.recordId ? ghlUrl("/objects/" + CONFIG.objectKeys.quarters + "/list?recordId=" + r.recordId) : LIST_URLS.quarters; },
      training: function (r) { return r.recordId ? ghlUrl("/objects/" + CONFIG.objectKeys.training + "/list?recordId=" + r.recordId) : LIST_URLS.training; },
      maintenance: function (r) { return r.recordId ? ghlUrl("/objects/" + CONFIG.objectKeys.maintenance + "/list?recordId=" + r.recordId) : LIST_URLS.maintenance; },
      aaa: function (r) { return r.recordId ? ghlUrl("/objects/" + CONFIG.objectKeys.aaa + "/list?recordId=" + r.recordId) : LIST_URLS.aaa; },
    };
    function listLink(key) { return function () { return LIST_URLS[key]; }; }

    var ICONS = {
      dispatch: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M12 21s6.5-6.9 6.5-11.5A6.5 6.5 0 0 0 5.5 9.5C5.5 14.1 12 21 12 21z"></path><circle cx="12" cy="9.5" r="2.3"></circle></svg>',
      aaa: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><rect x="2.5" y="5.5" width="19" height="13" rx="2"></rect><line x1="2.5" y1="9.5" x2="21.5" y2="9.5"></line><line x1="5.5" y1="14.5" x2="9.5" y2="14.5"></line></svg>',
      drivers: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="8" r="3.6"></circle><path d="M4.5 20c0-4.14 3.36-7.5 7.5-7.5s7.5 3.36 7.5 7.5"></path></svg>',
      trucks: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><rect x="2" y="7" width="11" height="9" rx="1"></rect><path d="M13 10h4l4 3.2V16h-8"></path><circle cx="6.5" cy="18" r="1.7"></circle><circle cx="16.5" cy="18" r="1.7"></circle></svg>',
    };

    var SECTION_META = {
      dispatch: { title: "Dispatch", desc: "Live jobs from your Towing Dispatch pipeline in GHL.", subs: null },
      aaa: { title: "AAA Payments", desc: "Reconciliation between AAA's payouts and your expected tow amounts.", subs: null },
      drivers: {
        title: "Drivers",
        desc: "Everything about who's behind the wheel — profiles, performance, pay, and training.",
        subs: [
          { id: "profiles", label: "Profiles" },
          { id: "performance", label: "Performance" },
          { id: "commissions", label: "Commissions" },
          { id: "training", label: "Training" },
        ],
      },
      trucks: {
        title: "Trucks",
        desc: "Your fleet, who's driving what, and what's due for service.",
        subs: [
          { id: "fleet", label: "Fleet" },
          { id: "assignments", label: "Assignments" },
          { id: "maintenance", label: "Maintenance" },
        ],
      },
    };

    var view = { section: "home", sub: null };
    var searchUidCounter = 1;

    var pulseStripEl = root.querySelector("#pulseStrip");
    var homeEl = root.querySelector("#home");
    var overviewHeadingEl = root.querySelector("#overviewHeading");
    var overviewEl = root.querySelector("#overview");
    var sectionEl = root.querySelector("#section");
    var crumbEl = root.querySelector("#crumb");
    var sectionTitleEl = root.querySelector("#sectionTitle");
    var sectionDescEl = root.querySelector("#sectionDesc");
    var subnavEl = root.querySelector("#subnav");
    var sectionBodyEl = root.querySelector("#sectionBody");
    var syncTextEl = root.querySelector("#syncText");
    var refreshBtnEl = root.querySelector("#refreshBtn");
    var setupLinkEl = root.querySelector("#setupLink");

    if (setupLinkEl) {
      if (CONFIG.setupUrl) setupLinkEl.href = CONFIG.setupUrl;
      else setupLinkEl.hidden = true;
    }

    var refreshing = false;
    function doRefresh() {
      if (refreshing) return;
      refreshing = true;
      refreshBtnEl && refreshBtnEl.classList.add("spinning");
      syncTextEl.textContent = "Refreshing…";
      loadAll()
        .then(function () {
          render();
        })
        .catch(function (err) {
          console.error("[CJT Dashboard] refresh failed:", err);
          syncTextEl.textContent = "Refresh failed — see console";
        })
        .finally(function () {
          refreshing = false;
          refreshBtnEl && refreshBtnEl.classList.remove("spinning");
        });
    }
    refreshBtnEl && refreshBtnEl.addEventListener("click", doRefresh);

    homeEl.addEventListener("click", function (e) {
      var btn = e.target.closest(".hubcard");
      if (btn) navigate(btn.dataset.nav, btn.dataset.sub || null);
    });

    function navigate(section, sub) {
      var meta = SECTION_META[section];
      view.section = section;
      view.sub = sub || (meta && meta.subs ? meta.subs[0].id : null);
      render();
      try { window.scrollTo({ top: 0, behavior: "instant" }); } catch (e) {}
    }

    function esc(v) {
      if (v === null || v === undefined || v === "") return "&mdash;";
      return String(v).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
    }
    function escAttr(v) {
      return String(v).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
    }
    function money(v) {
      if (v === null || v === undefined) return "&mdash;";
      var n = Number(v);
      if (isNaN(n)) return esc(v);
      return '<span class="mono">$' + n.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 }) + "</span>";
    }
    function pill(v) {
      if (v === null || v === undefined || v === "") return "&mdash;";
      var key = String(v).toLowerCase().replace(/\s+/g, "_");
      return '<span class="status-pill status-' + key + '">' + esc(v) + "</span>";
    }
    function dateOnly(v) {
      if (!v) return "&mdash;";
      var d = new Date(v);
      if (isNaN(d.getTime())) return esc(v);
      return '<span class="mono">' + d.toLocaleDateString(undefined, { year: "numeric", month: "short", day: "numeric" }) + "</span>";
    }

    function actionBtn(a) {
      var cls = "ghllink" + (a.primary ? " primary" : "");
      return '<a class="' + cls + '" href="' + escAttr(a.url) + '" target="_blank" rel="noopener">' + esc(a.label) + "</a>";
    }
    function panelHead(note, actions) {
      var btns = (actions || []).map(actionBtn).join("");
      return '<div class="panel-head"><div class="panel-note">' + note + '</div><div class="panel-actions">' + btns + "</div></div>";
    }

    function buildTable(columns, rows, linkFn) {
      if (!rows || !rows.length) {
        return '<div class="tableWrap"><div class="empty">No records synced for this yet.</div></div>';
      }
      var head = columns.map(function (c) { return "<th>" + c.label + "</th>"; }).join("");
      var body = rows.map(function (r) {
        var url = linkFn ? linkFn(r) : null;
        var cells = columns.map(function (c, i) {
          var html = c.render(r);
          if (url) {
            var cls = i === 0 ? "rowlink" : "cellLink";
            html = '<a class="' + cls + '" href="' + escAttr(url) + '" target="_blank" rel="noopener">' + html + "</a>";
          }
          return "<td>" + html + "</td>";
        }).join("");
        var trOpen = url ? '<tr class="clickable">' : "<tr>";
        return trOpen + cells + "</tr>";
      }).join("");
      return '<div class="tableWrap"><table><thead><tr>' + head + "</tr></thead><tbody>" + body + "</tbody></table></div>";
    }

    function mountSearch(container, opts) {
      var uid = "flt" + searchUidCounter++;
      var rows = opts.rows || [];
      container.innerHTML =
        (opts.headHtml || "") +
        '<div class="searchRow"><input type="text" class="searchInput" id="' + uid + '" placeholder="' + escAttr(opts.placeholder || "Search…") + '"></div>' +
        '<div id="' + uid + '-wrap">' + buildTable(opts.columns, rows, opts.linkFn) + "</div>";
      var input = container.querySelector("#" + uid);
      var wrap = container.querySelector("#" + uid + "-wrap");
      if (input) {
        input.addEventListener("input", function () {
          var q = input.value.trim().toLowerCase();
          var filtered = !q ? rows : rows.filter(function (r) { return JSON.stringify(r).toLowerCase().indexOf(q) !== -1; });
          wrap.innerHTML = buildTable(opts.columns, filtered, opts.linkFn);
        });
      }
    }

    function stageSummary(stageCounts) {
      var keys = Object.keys(stageCounts || {});
      if (!keys.length) return "No open jobs synced";
      return keys.map(function (k) { return k + " (" + stageCounts[k] + ")"; }).join(" · ");
    }

    function daysUntil(dateStr) {
      if (!dateStr) return null;
      var d = new Date(dateStr);
      if (isNaN(d.getTime())) return null;
      var now = new Date();
      d.setHours(0, 0, 0, 0);
      now.setHours(0, 0, 0, 0);
      return Math.round((d - now) / 86400000);
    }
    function dueBadge(days) {
      if (days === null) return "";
      if (days < 0) return '<span class="due-badge due-overdue">' + Math.abs(days) + "d overdue</span>";
      if (days === 0) return '<span class="due-badge due-today">Due today</span>';
      if (days <= 14) return '<span class="due-badge due-soon">In ' + days + "d</span>";
      return '<span class="due-badge due-later">In ' + days + "d</span>";
    }
    function daysAgoLabel(dateStr) {
      if (!dateStr) return "";
      var d = new Date(dateStr);
      if (isNaN(d.getTime())) return "";
      var days = Math.floor((new Date() - d) / 86400000);
      if (days <= 0) return "Today";
      if (days === 1) return "1 day ago";
      return days + " days ago";
    }
    function diffChip(diff) {
      var n = Number(diff);
      if (isNaN(n) || n === 0) return "";
      var cls = n > 0 ? "amber" : "red";
      var sign = n > 0 ? "+" : "−";
      var amt = "$" + Math.abs(n).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 });
      return '<span class="chip ' + cls + '">' + sign + amt + "</span>";
    }
    function prefersReducedMotion() {
      return !!(window.matchMedia && window.matchMedia("(prefers-reduced-motion: reduce)").matches);
    }
    function animateValueText(el, finalText) {
      var m = String(finalText).match(/^(\$?)([\d,]+(?:\.\d+)?)(.*)$/);
      if (!m || prefersReducedMotion()) {
        el.textContent = finalText;
        return;
      }
      var prefix = m[1], numStr = m[2], suffix = m[3];
      var target = parseFloat(numStr.replace(/,/g, ""));
      if (isNaN(target)) {
        el.textContent = finalText;
        return;
      }
      var decimals = numStr.indexOf(".") !== -1 ? (numStr.split(".")[1] || "").length : 0;
      var duration = 650;
      var start = null;
      function step(ts) {
        if (start === null) start = ts;
        var progress = Math.min((ts - start) / duration, 1);
        var eased = 1 - Math.pow(1 - progress, 3);
        el.textContent = prefix + (target * eased).toLocaleString(undefined, { minimumFractionDigits: decimals, maximumFractionDigits: decimals }) + suffix;
        if (progress < 1) requestAnimationFrame(step);
        else {
          el.textContent = finalText;
          el.classList.add("pulseIn");
          setTimeout(function () { el.classList.remove("pulseIn"); }, 700);
        }
      }
      requestAnimationFrame(step);
    }

    function renderPulseStrip() {
      var dispatch = state.dispatch || {};
      var jobs = dispatch.opportunities || [];
      var pipelineValue = jobs.reduce(function (sum, r) { var n = Number(r.value); return sum + (isNaN(n) ? 0 : n); }, 0);

      var exceptions = ((state.aaaSamples || {}).exceptions || []).filter(function (r) { return r.diff !== null && r.diff !== undefined && r.diff !== 0; });
      var exceptionsAtRisk = exceptions.reduce(function (sum, r) { var n = Number(r.diff); return sum + (isNaN(n) ? 0 : Math.abs(n)); }, 0);

      var drivers = (state.drivers || {}).records || [];
      var driversActive = drivers.filter(function (d) { return (d.status || "").toLowerCase() === "active"; }).length;
      var driverPct = drivers.length ? Math.round((driversActive / drivers.length) * 100) : null;

      var maint = (state.maintenance || {}).records || [];
      var dueSoon = maint.filter(function (r) { var d = daysUntil(r.nextService); return d !== null && d <= 14; }).length;

      var tiles = [
        { label: "Pipeline value", dot: "info", value: "$" + pipelineValue.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 }), sub: jobs.length + " open jobs" },
        { label: "Exceptions at risk", dot: exceptionsAtRisk > 0 ? "warn" : "good", value: "$" + exceptionsAtRisk.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 }), sub: exceptions.length + " flagged payment" + (exceptions.length === 1 ? "" : "s") },
        { label: "Driver availability", dot: driverPct === null ? "info" : (driverPct >= 80 ? "good" : "warn"), value: driverPct === null ? "—" : driverPct + "%", sub: drivers.length ? driversActive + " of " + drivers.length + " active" : "No drivers synced" },
        { label: "Trucks due soon", dot: dueSoon > 0 ? "warn" : "good", value: String(dueSoon), sub: "Maintenance within 14 days" },
      ];

      pulseStripEl.hidden = false;
      pulseStripEl.innerHTML = tiles.map(function (t) {
        return (
          '<div class="pulse-tile"><div class="pulse-label"><span class="dot ' + t.dot + '"></span>' + esc(t.label) + "</div>" +
          '<div class="pulse-value">' + esc(t.value) + "</div>" +
          '<div class="pulse-sub">' + esc(t.sub) + "</div></div>"
        );
      }).join("");

      Array.prototype.forEach.call(pulseStripEl.querySelectorAll(".pulse-tile"), function (tile, i) {
        var valEl = tile.querySelector(".pulse-value");
        if (valEl) animateValueText(valEl, tiles[i].value);
      });
    }

    function miniPanel(title, bodyHtml) {
      return '<div class="miniPanel"><div class="miniTitle">' + esc(title) + '</div><div class="miniList">' + bodyHtml + "</div></div>";
    }
    function miniRow(titleText, badgeHtml, detailHtml, url) {
      return (
        '<a class="miniRow clickable" href="' + escAttr(url) + '" target="_blank" rel="noopener">' +
        '<span class="miniRowMain"><span class="miniRowTitle">' + esc(titleText) + ' <span class="miniRowArrow">↗</span></span><span class="miniRowDetail">' + (detailHtml || "") + "</span></span>" +
        '<span class="miniRowBadge">' + (badgeHtml || "") + "</span>" +
        "</a>"
      );
    }

    function renderOverview() {
      var dispatch = state.dispatch || {};
      var recentJobs = (dispatch.opportunities || []).slice().sort(function (a, b) { return new Date(b.updatedAt) - new Date(a.updatedAt); }).slice(0, 5);

      var exceptions = ((state.aaaSamples || {}).exceptions || [])
        .filter(function (r) { return r.diff !== null && r.diff !== undefined && r.diff !== 0; })
        .sort(function (a, b) { return Math.abs(b.diff) - Math.abs(a.diff); })
        .slice(0, 5);

      var drivers = (state.drivers || {}).records || [];
      var driversOut = drivers.filter(function (d) { return (d.status || "").toLowerCase() !== "active"; });
      var driversActiveCount = drivers.length - driversOut.length;

      var maint = (state.maintenance || {}).records || [];
      var upcoming = maint.filter(function (r) { return r.nextService; }).slice().sort(function (a, b) { return new Date(a.nextService) - new Date(b.nextService); }).slice(0, 5);

      var dispatchBody = recentJobs.length
        ? recentJobs.map(function (r) { return miniRow(r.name, pill(r.stage), daysAgoLabel(r.updatedAt), LINK_FNS.dispatch(r) || LIST_URLS.dispatch); }).join("")
        : miniRow("No dispatch activity synced", "", "View pipeline", LIST_URLS.dispatch);

      var paymentsBody = exceptions.length
        ? exceptions.map(function (r) { return miniRow(r.wo ? "WO " + r.wo : r.id, diffChip(r.diff), esc(r.reason || (r.diff > 0 ? "Overpaid by AAA" : "Underpaid by AAA")), LINK_FNS.aaa(r) || LIST_URLS.aaa); }).join("")
        : miniRow("No exceptions flagged", "", "View AAA payments", LIST_URLS.aaa);

      var driversBody =
        '<div class="miniStat">' + driversActiveCount + " active · " + driversOut.length + " out</div>" +
        (driversOut.length
          ? driversOut.map(function (r) { return miniRow(r.name, pill(r.status), esc(r.type), LIST_URLS.drivers); }).join("")
          : miniRow("Everyone's active today", "", "View driver roster", LIST_URLS.drivers));

      var maintBody = upcoming.length
        ? upcoming.map(function (r) {
            var days = daysUntil(r.nextService);
            return miniRow("Truck " + r.truck + " — " + String(r.type || "").replace(/_/g, " "), dueBadge(days), dateOnly(r.nextService), LIST_URLS.maintenance);
          }).join("")
        : miniRow("Nothing scheduled", "", "View maintenance records", LIST_URLS.maintenance);

      overviewEl.innerHTML =
        miniPanel("Recent dispatch activity", dispatchBody) +
        miniPanel("Payments needing a look", paymentsBody) +
        miniPanel("Driver availability", driversBody) +
        miniPanel("Upcoming maintenance", maintBody);
    }

    function renderHome() {
      var dispatch = state.dispatch || {};
      var stageCounts = dispatch.stageCounts || {};
      var aaa = state.aaaSummary || {};
      var sc = aaa.status_counts || {};
      var meta = state.meta || {};
      var counts = meta.objectCounts || {};
      var driversTotal = (state.drivers && state.drivers.total) || counts.drivers || 0;
      var fleetTotal = (state.fleet && state.fleet.total) || counts.fleet || 0;

      var cards = [
        { nav: "dispatch", sub: null, icon: ICONS.dispatch, live: true, title: "Dispatch", value: (dispatch.total || 0) + " jobs", detail: stageSummary(stageCounts) },
        { nav: "aaa", sub: null, icon: ICONS.aaa, live: true, title: "AAA Payments", value: (aaa.total || 0).toLocaleString() + " imported", detail: (aaa.total ? "" : "No summary yet — ") + (sc.exception || 0) + " exceptions, " + (sc.matched || 0) + " matched" },
        { nav: "drivers", sub: "profiles", icon: ICONS.drivers, live: true, title: "Drivers", value: driversTotal + " profiles", detail: "Profiles · Performance · Commissions · Training" },
        { nav: "trucks", sub: "fleet", icon: ICONS.trucks, live: true, title: "Trucks", value: fleetTotal + " in fleet", detail: "Fleet · Assignments · Maintenance" },
      ];

      homeEl.innerHTML = cards.map(function (c) {
        return (
          '<button class="hubcard" data-nav="' + c.nav + '" data-sub="' + (c.sub || "") + '">' +
          '<div class="htitle"><span class="htitle-left"><span class="icon">' + c.icon + "</span>" + esc(c.title) + "</span>" + (c.live ? '<span class="livepill">Live</span>' : "") + "</div>" +
          '<div class="hvalue">' + esc(c.value) + "</div>" +
          '<div class="hdetail">' + esc(c.detail) + "</div>" +
          '<div class="chevron">Open →</div>' +
          "</button>"
        );
      }).join("");

      Array.prototype.forEach.call(homeEl.querySelectorAll(".hubcard"), function (btn, i) {
        var valEl = btn.querySelector(".hvalue");
        if (valEl) animateValueText(valEl, cards[i].value);
      });
    }

    function renderCrumb() {
      var meta = SECTION_META[view.section];
      crumbEl.innerHTML = '<button class="crumbBtn" id="crumbHome">← Dashboard</button><span class="crumbSep">/</span><span class="crumbCurrent">' + esc(meta.title) + "</span>";
      crumbEl.querySelector("#crumbHome").addEventListener("click", function () { navigate("home", null); });
      sectionTitleEl.textContent = meta.title;
      sectionDescEl.textContent = meta.desc;
    }

    function renderSubnav() {
      var meta = SECTION_META[view.section];
      if (!meta.subs) {
        subnavEl.hidden = true;
        subnavEl.innerHTML = "";
        return;
      }
      subnavEl.hidden = false;
      subnavEl.innerHTML = meta.subs.map(function (s) {
        return '<button data-sub="' + s.id + '" class="' + (view.sub === s.id ? "active" : "") + '">' + esc(s.label) + "</button>";
      }).join("");
      Array.prototype.forEach.call(subnavEl.querySelectorAll("button"), function (btn) {
        btn.addEventListener("click", function () { navigate(view.section, btn.dataset.sub); });
      });
    }

    function bodyDispatch() {
      var d = state.dispatch || {};
      var stageCounts = d.stageCounts || {};
      var chips = Object.keys(stageCounts).map(function (k) { return '<span class="chip">' + esc(k) + " <b>" + stageCounts[k] + "</b></span>"; }).join("");
      var cols = [
        { label: "Job / WO", render: function (r) { return esc(r.name); } },
        { label: "Stage", render: function (r) { return pill(r.stage); } },
        { label: "Status", render: function (r) { return esc(r.status); } },
        { label: "Value", render: function (r) { return money(r.value); } },
        { label: "Last updated", render: function (r) { return dateOnly(r.updatedAt); } },
      ];
      var head =
        panelHead('<span class="live-tag">● Live</span> — Pipeline: <b>' + esc(d.pipelineName || "—") + "</b>. Click a job to open its contact in GHL.", [{ label: "Open in GHL ↗", url: LIST_URLS.dispatch }]) +
        '<div class="chipRow">' + chips + "</div>";
      mountSearch(sectionBodyEl, { columns: cols, rows: d.opportunities || [], linkFn: LINK_FNS.dispatch, placeholder: "Search jobs by name or work order…", headHtml: head });
    }

    function bodyAaa() {
      var s = state.aaaSummary || {};
      var sc = s.status_counts || {};
      var samples = state.aaaSamples || {};
      var chips = [
        '<span class="chip accent">Matched <b>' + (sc.matched || 0) + "</b></span>",
        '<span class="chip amber">Unmatched <b>' + (sc.unmatched || 0) + "</b></span>",
        '<span class="chip red">Exception <b>' + (sc.exception || 0) + "</b></span>",
        '<span class="chip info">Awaiting match <b>' + (sc.unknown || 0) + "</b></span>",
      ].join("");
      var cols = [
        { label: "Payment ID", render: function (r) { return esc(r.id); } },
        { label: "Work order", render: function (r) { return esc(r.wo); } },
        { label: "Status", render: function (r) { return pill(r.status); } },
        { label: "Gross paid", render: function (r) { return money(r.gross); } },
        { label: "Expected", render: function (r) { return money(r.expected); } },
        { label: "Diff", render: function (r) { return money(r.diff); } },
        { label: "Reason", render: function (r) { return esc(r.reason); } },
      ];
      var linkFn = LINK_FNS.aaa;
      sectionBodyEl.innerHTML =
        panelHead('<span class="live-tag">● Live</span> — ' + (s.total || 0).toLocaleString() + " AAA payment records imported. " + (s.missing_work_order || 0) + " are missing a work order number.", [{ label: "Open in GHL ↗", url: LIST_URLS.aaa }]) +
        '<div class="chipRow">' + chips + "</div>" +
        '<h3 class="subhead">Exceptions</h3>' + buildTable(cols, samples.exceptions, linkFn) +
        '<h3 class="subhead">Matched (sample)</h3>' + buildTable(cols, samples.unmatched, linkFn);
    }

    function bodyDriversProfiles() {
      var d = state.drivers || {};
      var cols = [
        { label: "Name", render: function (r) { return esc(r.name); } },
        { label: "Driver ID", render: function (r) { return '<span class="mono">' + esc(r.driverId) + "</span>"; } },
        { label: "Status", render: function (r) { return pill(r.status); } },
        { label: "Type", render: function (r) { return esc(r.type); } },
        { label: "Hire date", render: function (r) { return dateOnly(r.hireDate); } },
        { label: "Email", render: function (r) { return esc(r.email); } },
      ];
      var head = panelHead(
        '<span class="live-tag">● Live</span> — Driver Profile custom object in GHL, ' + (d.total || 0) + " on file.",
        [{ label: "Open in GHL ↗", url: LIST_URLS.drivers }, { label: "+ Add Driver ↗", url: LIST_URLS.drivers, primary: true }]
      );
      mountSearch(sectionBodyEl, { columns: cols, rows: d.records || [], linkFn: LINK_FNS.drivers, placeholder: "Search drivers…", headHtml: head });
    }

    function bodyDriversPerformance() {
      var d = state.quarters || {};
      var cols = [
        { label: "Driver", render: function (r) { return esc(r.driver); } },
        { label: "Quarter", render: function (r) { return esc((r.quarter || "").toUpperCase() + " " + (r.year || "")); } },
        { label: "Jobs (done/total)", render: function (r) { return '<span class="mono">' + esc((r.completedJobs != null ? r.completedJobs : "—") + " / " + (r.totalJobs != null ? r.totalJobs : "—")) + "</span>"; } },
        { label: "Rating", render: function (r) { return pill(r.rating); } },
        { label: "Status", render: function (r) { return pill(r.status); } },
      ];
      sectionBodyEl.innerHTML =
        panelHead('<span class="live-tag">● Live</span> — Driver Quarter custom object in GHL, performance view.', [{ label: "Open in GHL ↗", url: LIST_URLS.quarters }]) +
        buildTable(cols, d.records || [], LINK_FNS.quarters);
    }

    function bodyDriversCommissions() {
      var d = state.quarters || {};
      var cols = [
        { label: "Driver", render: function (r) { return esc(r.driver); } },
        { label: "Quarter", render: function (r) { return esc((r.quarter || "").toUpperCase() + " " + (r.year || "")); } },
        { label: "Revenue", render: function (r) { return money(r.revenue); } },
        { label: "Commission", render: function (r) { return money(r.commission); } },
        { label: "Net commission", render: function (r) { return money(r.netCommission); } },
        { label: "Status", render: function (r) { return pill(r.status); } },
      ];
      sectionBodyEl.innerHTML =
        panelHead('<span class="live-tag">● Live</span> — Driver Quarter custom object in GHL, commission view.', [{ label: "Open in GHL ↗", url: LIST_URLS.quarters }]) +
        buildTable(cols, d.records || [], LINK_FNS.quarters);
    }

    function bodyDriversTraining() {
      var d = state.training || {};
      var cols = [
        { label: "Record", render: function (r) { return '<span class="mono">' + esc(r.id) + "</span>"; } },
        { label: "Driver", render: function (r) { return esc(r.driver); } },
        { label: "Title", render: function (r) { return esc(r.title); } },
        { label: "Type", render: function (r) { return esc(r.type); } },
        { label: "Date", render: function (r) { return dateOnly(r.date); } },
        { label: "Status", render: function (r) { return pill(r.status); } },
      ];
      sectionBodyEl.innerHTML =
        panelHead('<span class="live-tag">● Live</span> — Training Record custom object in GHL.', [{ label: "Open in GHL ↗", url: LIST_URLS.training }]) +
        buildTable(cols, d.records || [], LINK_FNS.training);
    }

    function bodyTrucksFleet() {
      var d = state.fleet || {};
      var cols = [
        { label: "Unit", render: function (r) { return '<span class="mono">' + esc(r.unit) + "</span>"; } },
        { label: "Vehicle", render: function (r) { return esc([r.yr, r.make, r.model].filter(Boolean).join(" ")); } },
        { label: "Status", render: function (r) { return pill(r.status); } },
        { label: "Mileage", render: function (r) { return r.mileage != null ? '<span class="mono">' + Number(r.mileage).toLocaleString() + "</span>" : "&mdash;"; } },
        { label: "Driver", render: function (r) { return esc(r.driver); } },
        { label: "Next service", render: function (r) { return dateOnly(r.nextService); } },
        { label: "Registration exp.", render: function (r) { return dateOnly(r.regExp); } },
        { label: "Insurance exp.", render: function (r) { return dateOnly(r.insExp); } },
      ];
      var head = panelHead(
        '<span class="live-tag">● Live</span> — Truck / Fleet custom object in GHL.',
        [{ label: "Open in GHL ↗", url: LIST_URLS.fleet }, { label: "+ Add Truck ↗", url: LIST_URLS.fleet, primary: true }]
      );
      mountSearch(sectionBodyEl, { columns: cols, rows: d.records || [], linkFn: LINK_FNS.fleet, placeholder: "Search fleet…", headHtml: head });
    }

    function bodyTrucksAssignments() {
      var d = state.fleet || {};
      var rows = (d.records || []).filter(function (r) { return r.driver; });
      var cols = [
        { label: "Driver", render: function (r) { return esc(r.driver); } },
        { label: "Unit", render: function (r) { return '<span class="mono">' + esc(r.unit) + "</span>"; } },
        { label: "Vehicle", render: function (r) { return esc([r.yr, r.make, r.model].filter(Boolean).join(" ")); } },
        { label: "Status", render: function (r) { return pill(r.status); } },
        { label: "Next service", render: function (r) { return dateOnly(r.nextService); } },
      ];
      sectionBodyEl.innerHTML =
        panelHead("Current truck-to-driver assignments, derived from the Fleet object.", [{ label: "Open in GHL ↗", url: LIST_URLS.fleet }]) +
        buildTable(cols, rows, LINK_FNS.fleet);
    }

    function bodyTrucksMaintenance() {
      var d = state.maintenance || {};
      var cols = [
        { label: "Record", render: function (r) { return '<span class="mono">' + esc(r.id) + "</span>"; } },
        { label: "Truck", render: function (r) { return esc(r.truck); } },
        { label: "Type", render: function (r) { return esc(r.type); } },
        { label: "Service date", render: function (r) { return dateOnly(r.serviceDate); } },
        { label: "Cost", render: function (r) { return money(r.cost); } },
        { label: "Status", render: function (r) { return pill(r.status); } },
        { label: "Next service", render: function (r) { return dateOnly(r.nextService); } },
        { label: "Provider", render: function (r) { return esc(r.provider); } },
      ];
      sectionBodyEl.innerHTML =
        panelHead('<span class="live-tag">● Live</span> — Maintenance Record custom object in GHL.', [{ label: "Open in GHL ↗", url: LIST_URLS.maintenance }]) +
        buildTable(cols, d.records || [], LINK_FNS.maintenance);
    }

    var BODY_RENDERERS = {
      dispatch: bodyDispatch,
      aaa: bodyAaa,
      "drivers:profiles": bodyDriversProfiles,
      "drivers:performance": bodyDriversPerformance,
      "drivers:commissions": bodyDriversCommissions,
      "drivers:training": bodyDriversTraining,
      "trucks:fleet": bodyTrucksFleet,
      "trucks:assignments": bodyTrucksAssignments,
      "trucks:maintenance": bodyTrucksMaintenance,
    };

    function renderSectionBody() {
      var key = view.section + (view.sub ? ":" + view.sub : "");
      var fn = BODY_RENDERERS[key] || BODY_RENDERERS[view.section];
      if (fn) fn();
      else sectionBodyEl.innerHTML = '<div class="empty">Nothing here yet.</div>';
    }

    function updateSyncBadge() {
      if (state.meta && state.meta.lastSynced) {
        var d = new Date(state.meta.lastSynced);
        syncTextEl.textContent = "Synced " + (isNaN(d.getTime()) ? state.meta.lastSynced : d.toLocaleString());
      } else {
        syncTextEl.textContent = "Not synced yet";
      }
    }

    function render() {
      updateSyncBadge();
      if (view.section === "home") {
        pulseStripEl.hidden = false;
        homeEl.hidden = false;
        overviewHeadingEl.hidden = false;
        overviewEl.hidden = false;
        sectionEl.hidden = true;
        renderPulseStrip();
        renderHome();
        renderOverview();
      } else {
        pulseStripEl.hidden = true;
        homeEl.hidden = true;
        overviewHeadingEl.hidden = true;
        overviewEl.hidden = true;
        sectionEl.hidden = false;
        renderCrumb();
        renderSubnav();
        renderSectionBody();
        sectionEl.classList.remove("animateIn");
        void sectionEl.offsetWidth;
        sectionEl.classList.add("animateIn");
      }
    }

    function showUnavailable(message) {
      pulseStripEl.hidden = true;
      homeEl.hidden = false;
      overviewHeadingEl.hidden = true;
      overviewEl.hidden = true;
      sectionEl.hidden = true;
      homeEl.innerHTML = '<div class="empty" style="grid-column:1/-1;">' + esc(message) + "</div>";
      syncTextEl.textContent = "Unavailable";
    }

    render();
    if (!CONFIG.locationId || !CONFIG.privateToken) {
      showUnavailable("This dashboard isn't configured yet — set locationId and privateToken in window.CJT_CONFIG. Use the Setup page to generate this.");
      return;
    }
    doRefresh();
  }
})();
